buildpacks/docs

docs/categories/index.html
docs/docs/app-journey/index.html
docs/docs/create-buildpack/build-app/index.html
docs/docs/create-buildpack/building-blocks-cnb/index.html
docs/docs/create-buildpack/caching/index.html
docs/docs/create-buildpack/detection/index.html
docs/docs/create-buildpack/index.html
docs/docs/create-buildpack/make-app-runnable/index.html
docs/docs/create-buildpack/setup-local-environment/index.html
docs/docs/index.html
docs/docs/install-pack/index.html
docs/docs/using-pack/building-app/index.html
docs/docs/using-pack/index.html
docs/docs/using-pack/managing-stacks/index.html
docs/docs/using-pack/update-app-rebase/index.html
docs/docs/using-pack/working-with-builders/index.html
docs/index.html
docs/scss/site.css
docs/tags/index.html
src/config.toml
src/resources/_gen/assets/scss/scss/site.scss_f300667da4f5b5f84e1a9e0702b2fdde.content
src/themes/buildpacks/assets/scss/_base.scss
src/themes/buildpacks/assets/scss/components/_header.scss
src/themes/buildpacks/layouts/partials/header.html

Waiting on the URL for the navigation, but this PR adds a link to blog to the header.

Adds blog to navigation

---

docs/docs/using-pack/index.html
src/content/docs/using-pack/_index.md

Align with recent README change

---

content/docs/using-pack/working-with-builders.md

Update create-builder docs

---

.gitignore
README.md
config.toml
content/docs/app-journey/_index.md
content/docs/install-pack/_index.md
themes/buildpacks/assets/scss/_syntax.scss
themes/buildpacks/assets/scss/components/_text-note.scss
themes/buildpacks/assets/scss/site.scss

- Add syntax highlighting
- Style blockquotes

Improve 'Installing pack'

---

content/docs/app-journey/_index.md

Improve app journey

---

content/docs/using-pack/_index.md
content/docs/using-pack/building-app.md
content/docs/using-pack/stacks.md
content/docs/using-pack/working-with-builders.md
themes/buildpacks/assets/scss/_code.scss
themes/buildpacks/assets/scss/_syntax.scss
themes/buildpacks/assets/scss/_typography.scss
themes/buildpacks/assets/scss/components/_docs.scss
themes/buildpacks/assets/scss/components/_table.scss
themes/buildpacks/assets/scss/site.scss

Document custom stacks

---

config.toml
themes/buildpacks/layouts/_default/baseof.html
themes/buildpacks/layouts/partials/meta.html

This PR adds some basic SEO metadata for the site, which should help out with its placement in search results

Add OpenGraph and Twitter Card metadata

---

README.md

Add instructions for editing documentation

---

src/content/docs/_index.md

@sclevine Let me know if this is acceptable or if you desire further styling.

Add Videos to Buildpacks docs page

---

content/docs/create-buildpack/building-blocks-cnb.md
content/docs/using-pack/building-app.md
content/docs/using-pack/stacks.md
content/docs/using-pack/working-with-builders.md

Update toml-related docs and other minor polish
NOTE: This is a PR for `edge` branch, as it is for staging for the upcoming `0.4.0` release of `pack`.

Update toml-related docs

---

content/docs/app-journey/_index.md

Use https url for git clone

---

.travis.yml
Makefile

Also:
* Use github token to query latest pack release
Resolves #54

Ensure Pack version is retrieved

---

content/docs/app-journey/_index.md

Hey,
I was just reading this doc & noticed this small spelling mistake so figured I'd open a PR to fix it 👌

Add missing d to BuildPack in link

---

content/docs/_index.md
content/docs/create-buildpack/_index.md
content/docs/create-buildpack/build-app.md
content/docs/create-buildpack/building-blocks-cnb.md
content/docs/create-buildpack/caching.md
content/docs/create-buildpack/detection.md
content/docs/create-buildpack/make-app-runnable.md
content/docs/create-buildpack/make-buildpack-configurable.md
content/docs/create-buildpack/setup-local-environment.md
content/docs/install-pack/_index.md

Resolves #51 
- Works with pack 0.4.0 and lifecycle 0.4.0
- Broke out caching page into more digestable pages

Update buildpack creation tutorial

---

Makefile

Update latest pack version to not include drafts

---

content/docs/_index.md
content/docs/reference/_index.md
content/docs/reference/buildpack-api.md
content/docs/reference/distribution-api.md
content/docs/reference/platform-api.md

Fixes #11
I'm not sure if the Platform and Distribution pages are really needed. But I added them for completeness.

Add References docs

---

content/docs/buildpack-author-guide/create-buildpack/building-blocks-cnb.md

Sync number of builders used in examples

---

config.toml
content/docs/app-developer-guide/build-an-app.md
content/docs/app-developer-guide/environment-variables.md
content/docs/app-developer-guide/specific-buildpacks.md
content/docs/app-journey.md
content/docs/concepts/components/stack.md
content/docs/install-pack.md
content/docs/operator-guide/create-a-builder.md
content/docs/reference/buildpack-api.md
content/docs/reference/distribution-api.md
content/docs/reference/platform-api.md
themes/buildpacks/layouts/index.html
themes/buildpacks/layouts/partials/header.html

Rename Github org to github.com/buildpacks

---

content/docs/concepts/components/stack.md

Document mixins

---

README.md

Update travis badge and link based on reorg

---

Makefile
content/docs/_index.md

- Additional null check for PACK_VERSION
- Update project board link
Resolves #97

Additional changes due to org rename

---

Makefile
content/docs/reference/buildpack-api.md
themes/buildpacks/assets/scss/_colors.scss
themes/buildpacks/assets/scss/components/_content.scss
themes/buildpacks/assets/scss/components/_hero.scss
themes/buildpacks/layouts/index.html

* Rename/Remove Buildpack API v3 mentions
* Define buildpack.toml schema
* Define API compatibility rules
Resolves #82
Resolves #71
Resolves #66
<hr />

Clear up Buildpack API nomenclature

---

content/docs/buildpack-author-guide/create-buildpack/make-buildpack-configurable.md
content/docs/concepts/components/stack.md

Docs related to `pack` 0.6.0 features
Changes have already been reviewed via previous PRs into the release branch. That said, still look over this for any obvious issues.

0.6.0 docs

---

content/docs/app-developer-guide/environment-variables.md

Signed-off-by: Zander Mackie <zmackie@gmail.com>

Fix echo in example

---

content/docs/reference/builder-config.md
themes/buildpacks/assets/scss/components/_docs.scss
themes/buildpacks/layouts/_default/baseof.html

- Blocked by https://github.com/buildpacks/docs/pull/116
Signed-off-by: Zander Mackie <zmackie@gmail.com>

Updates builder docs to use anchor tags

---

content/docs/app-developer-guide/build-an-app.md

doc: fix typo in build-an-app.md

---

content/docs/app-developer-guide/specific-buildpacks.md
content/docs/operator-guide/create-a-builder.md
content/docs/reference/builder-config.md

Also, fix indentation in builder.toml schema (thanks @ameyer-pivotal)

Update sample buildpack IDs

---

.github/ISSUE_TEMPLATE/config.yml

* Close #110
If this looks good, I'll PR it as well into the pack and lifecycle

Direct users to slack when filing issues

---

.github/ISSUE_TEMPLATE/config.yml

Tweaks to the Slack contact link in issues

---

content/docs/install-pack.md

Change brew tap to buildpacks

---

content/docs/reference/builder-config.md

Add packaged buildpack to create-builder config

---

content/docs/app-journey.md

Signed-off-by: Christian Köberl <christian.koeberl@gmail.com>

Fix link to CNB Platform Specification

---

content/docs/_index.md
content/docs/reference/config/_index.md
content/docs/reference/config/builder-config.md
content/docs/reference/config/package-config.md
content/docs/reference/reproducibility.md
content/docs/reference/spec/_index.md
content/docs/reference/spec/buildpack-api.md
content/docs/reference/spec/distribution-api.md
content/docs/reference/spec/platform-api.md

- Organize getting started section
- Add contributor's guide
- Organize reference articles

Refresh getting started

---

themes/buildpacks/layouts/partials/support.html
tools/get_pack_commands.go

Fixes #172 
**Before:** 
**After:**

Remove edit button from generated pack pages

---

content/features.md
themes/buildpacks/assets/scss/components/_docs.scss
themes/buildpacks/layouts/shortcodes/comparison-table.html

- Replace "Build Cache" with "Advanced Caching".
- Replace "Composable" with "Modular / Pluggable".
- Add "N/A" where feature doesn't make sense for solution.
- Minor copy edits.

Clarify some features

---

content/docs/reference/pack/concepts/_index.md
content/docs/reference/pack/concepts/trusted_builders.md

- Add a 'Concepts' section for pack
Fixes #167
Signed-off-by: Simon Jones <simonjones@vmware.com>

Concept documentation for pack's trusted builders

---

content/docs/buildpack-author-guide/create-buildpack/caching.md

Signed-off-by: NAME <EMAIL_ADDRESS>

chore: Added missing option to mkdir

---

themes/buildpacks/layouts/index.html

Signed-off-by: Javier Romero <rjavier@vmware.com>
CC: @ameyer-pivotal

minor typo in tagline

---

content/docs/app-developer-guide/build-a-windows-app.md

- Make example more secure (+ small fix)
Signed-off-by: Micah Young <ymicah@vmware.com>

Clarify in Windows app that DOCKER_HOST is optional

---

content/docs/app-developer-guide/build-a-windows-app.md

Signed-off-by: Andrew Meyer <meyeran@vmware.com>

Fix minor header formatting issue

---

content/docs/app-developer-guide/mouting-volumes.md

Fixing volume's name

---

content/docs/tools/pack/concepts/trusted_builders.md

Signed-off-by: Anish Karandikar <anishkny@gmail.com>
> _By signing off you acknowledge adhering to the requirements listed here: https://github.com/apps/dco_

docs(Trusted builders): Fix broken command links

---

content/docs/buildpack-author-guide/create-buildpack/build-app.md
content/docs/buildpack-author-guide/create-buildpack/building-blocks-cnb.md
content/docs/buildpack-author-guide/create-buildpack/caching.md
content/docs/buildpack-author-guide/create-buildpack/detection.md
content/docs/buildpack-author-guide/create-buildpack/make-buildpack-configurable.md

Ths PR reverts changes from https://github.com/buildpacks/docs/pull/222 and makes a minor change to match newer output.

Add output checks back

---

content/docs/operator-guide/create-a-builder.md

Add mention of builder config in reference section

---

content/docs/tools/circleci.md
content/docs/tools/gitlab.md
content/docs/tools/pack/_index.md
content/docs/tools/tekton.md

Add docs for CircleCI, Gitlab, and Tekton

---

content/docs/reference/config/builder-config.md
content/docs/reference/config/package-config.md

Signed-off-by: Micah Young <ymicah@vmware.com>

Remove deprecated buildpackage syntax

---

content/docs/operator-guide/create-a-builder.md

Signed-off-by: James Bayer 1139532+jbayer@users.noreply.github.com

Example run command uses entrypoint

---

.github/workflows/main.yml

Fix CI deprecations

---

content/docs/app-developer-guide/specific-buildpacks.md

Updated "Specify buildpacks" with details from [RFC-0037](https://github.com/buildpacks/rfcs/blob/main/text/0037-buildpack-uris.md)

Added description of Buildpack URIs

---

data/pack/install.yml

Add Ubuntu PPA install instructions

---

content/docs/buildpack-author-guide/create-buildpack/building-blocks-cnb.md
content/docs/buildpack-author-guide/create-buildpack/caching.md
content/docs/buildpack-author-guide/create-buildpack/make-buildpack-configurable.md

Update the buildpack authors guide to use Buildpack API v0.5 and fix minor errors

---

content/docs/buildpack-author-guide/create-buildpack/_index.md
content/docs/buildpack-author-guide/create-buildpack/adding-bill-of-materials.md
content/docs/buildpack-author-guide/create-buildpack/make-buildpack-configurable.md

 Add a section about BOM in the buildpack authors guide

---

content/docs/tools/pack/_index.md

Taken from https://github.com/buildpacks/pack/blob/12ad9216b898c13e6cd806a7f6f3e9bb0e7cea9d/internal/commands/completion.go#L41

Add docs about shell completions for pack for alt. shells

---

content/docs/buildpack-author-guide/publishing-with-github-actions.md

It was using `pack package-buildpack`

Update buildpack package command to new format

---

content/docs/buildpack-author-guide/create-buildpack/build-app.md

I've talked with a few people who've asked "how do I create layers in my buildpack". I don't think the existing docs split this part out enough to make it understandable (and the current doc isn't something that's good to directly link to if you want answer that question).

Reworked the composition of build-app step in Buildpack author guide

---

content/docs/buildpack-author-guide/create-buildpack/adding-bill-of-materials.md
content/docs/buildpack-author-guide/create-buildpack/build-app.md
content/docs/buildpack-author-guide/create-buildpack/caching.md
content/docs/buildpack-author-guide/create-buildpack/make-app-runnable.md
content/docs/buildpack-author-guide/create-buildpack/make-buildpack-configurable.md
content/docs/buildpack-author-guide/create-buildpack/specify-multiple-process-types.md

Fix inconsistencies in docs

---

content/docs/concepts/components/stack.md
content/docs/operator-guide/create-a-builder.md
content/docs/operator-guide/create-a-stack.md

Fixes https://github.com/buildpacks/docs/issues/249

Add instructions on creating a stack in the operators guide

---

data/calendar.yml
themes/buildpacks/layouts/shortcodes/calendar.html

Add office hours to calendar

---

content/docs/concepts/components/builder.md

Fixed:
nescessary -> necessary

fix: typo of word necessary

---

content/docs/tools/kpack.md

Add kpack to the tools page

---

content/docs/app-developer-guide/using-cache-image.md

Fix typo with cache image name

---

content/docs/concepts/components/lifecycle/export.md
content/docs/reference/spec/migration/platform-api-0.5-0.6.md

Added report.toml but didn't push before the other PR was merged :)

Platform 0.5 0.6 migration additions

---

content/docs/concepts/components/lifecycle/_index.md
content/docs/concepts/components/lifecycle/analyze.md
content/docs/concepts/components/lifecycle/build.md
content/docs/concepts/components/lifecycle/create.md
content/docs/concepts/components/lifecycle/detect.md
content/docs/concepts/components/lifecycle/export.md
content/docs/concepts/components/lifecycle/launch.md
content/docs/concepts/components/lifecycle/rebase.md
content/docs/concepts/components/lifecycle/restore.md

Signed-off-by: Natalie Arellano <narellano@vmware.com>

Show summaries for lifecycle phases

---

content/docs/buildpack-author-guide/create-buildpack/_index.md
tools/go.mod
tools/go.sum

We should also merge https://github.com/buildpacks/katacoda-scenarios/pull/5 alongside this

Add link to BP Authors katacoda

---

config.toml

Add link to privacy policy

---

data/talks.yml

Fixes #370  partially.
Still missing the office hours slides.

Add CNB Kubecon EU 2021 talk

---

content/docs/buildpack-author-guide/create-buildpack/building-blocks-cnb.md

**Changes:**
- I added `Using the Pack CLI` section on building blocks-cnb page.
Resolves #307
**Preview:**

buildpack create command is added to docs.

---

content/docs/_index.md
data/talks.yml
themes/buildpacks/layouts/shortcodes/summary.html

- Add Office Hours slides (#369)
- Adds additional tools to list
- Moves Talks section to the top of the page
- Removes old intro video
Resolves #369

Update Getting Started page

---

content/docs/tools/tekton.md

Signed-off-by: Jason Hall <jasonhall@redhat.com>
Related: https://github.com/buildpacks/lifecycle/issues/608

Update docs for authing Docker pushes in Tekton

---

themes/buildpacks/layouts/shortcodes/tab.html
themes/buildpacks/layouts/shortcodes/tabs.html

Fix community tab display issue

---

content/docs/concepts/components/buildpack-group.md

This is my attempt to document buildpack groups. Thoughts and feedback are appreciated.
Resolves: #147

Adds a description for buildpack groups

---

DEVELOPMENT.md

This PR adds development prerequisites for Ubuntu users and make clean command

Adds development prerequisites for Ubuntu users and make clean command

---

themes/buildpacks/assets/scss/components/_sidebar.scss

This PR makes dynamic sticky side-bar;

Made side-bar sticky

---

.github/PR_TEMPLATE.md
.github/PR_TEMPLATE/pr_template.md

This PR adds template for pull request

Added PR_TEMPLATE

---

content/docs/app-developer-guide/using-inline-buildpacks.md
content/docs/reference/config/project-descriptor.md

**DO NOT MERGE** until after [Pack PR #1166](https://github.com/buildpacks/pack/pull/1166) is released.
Documents the implementation of [RFC-0048]() as realized in [spec PR #224](https://github.com/buildpacks/spec/pull/224) and implemented in [Pack PR #1166](https://github.com/buildpacks/pack/pull/1166)

Added documentation for inline buildpacks

---

content/docs/tools/tekton.md

Signed-off-by: Peter Mbanugo <p.mbanugo@yahoo.com>
The Tekton page in the docs is using outdated versions of buildpacks & git-clone. This PR is a re-write to update the version and some code snippets.

Update Buildpacks-Tekton integration guide

---

content/docs/concepts/components/lifecycle/analyze.md
content/docs/concepts/components/lifecycle/create.md
content/docs/concepts/components/lifecycle/detect.md
content/docs/reference/spec/migration/platform-api-0.6-0.7.md

- Document moving the analyze phase before the detect phase.
- Add a migration guide from platform API 0.6 to platform API 0.7.
Fixes #302.

Swap the analyze and detect phases

---

content/docs/concepts/components/buildpack.md

Signed-off-by: Anatoli Babenia <anatoli@rainforce.org>
I am trying to improve that once again.

Clarify buildpack description even more

---

.github/bug_report.md

Signed-off-by: Asmit2952 <asmitbm2952002@gmail.com>

This PR adds a bug report template

---

content/docs/buildpack-author-guide/create-buildpack/adding-bill-of-materials.md
content/docs/buildpack-author-guide/create-buildpack/build-app.md
content/docs/buildpack-author-guide/create-buildpack/building-blocks-cnb.md
content/docs/buildpack-author-guide/create-buildpack/caching.md
content/docs/buildpack-author-guide/create-buildpack/make-app-runnable.md
content/docs/buildpack-author-guide/create-buildpack/make-buildpack-configurable.md
content/docs/buildpack-author-guide/create-buildpack/specify-multiple-process-types.md

This PR is in response to issue #246 .
Purpose of this PR is to make changes to buildpack author tutorial for compatibility with Buildpack API 0.6.

Changes to Buildpack author tutorial for compatibility with Buildpack API 0.6

---

data/talks.yml

Add packaging con 2021 slides

---

content/docs/reference/spec/buildpack-api.md
content/docs/reference/spec/migration/buildpack-api-0.6-0.7.md
content/docs/reference/spec/migration/platform-api-0.7-0.8.md

Signed-off-by: Natalie Arellano <narellano@vmware.com>

Add migration guides for latest apis

---

data/talks.yml

Add youtube ID for PackagingCon talk

---

content/docs/reference/spec/buildpack-api.md

Signed-off-by: tgquan67 <tgquan67@gmail.com>

Change current buildpack API version to 0.7 in buildpack.toml schema documentation

---

content/features.md
themes/buildpacks/layouts/shortcodes/blog-cards.html
themes/buildpacks/layouts/shortcodes/in-depth-comparison-table.html

Adds initial layout for 1 on 1 comparison. (Work in progress)

Implement redesign of feature comparison

---

content/docs/buildpack-author-guide/create-buildpack/caching.md

This is for issue https://github.com/buildpacks/docs/issues/427

Actually capture the sha256sum instead.

---

themes/buildpacks/layouts/index.html

We can remove it when the survey closes in mid-January.

Add link to survey to homepage

---

content/features.md

Add standard sbom formats to features page

---

content/docs/reference/spec/migration/buildpack-api-0.6-0.7.md
content/docs/reference/spec/migration/platform-api-0.7-0.8.md

See https://github.com/buildpacks/spec/pull/286
Signed-off-by: Natalie Arellano <narellano@vmware.com>

Update migration guide to reflect sbom compat

---

content/docs/buildpack-author-guide/create-buildpack/adding-bill-of-materials.md
content/docs/buildpack-author-guide/create-buildpack/caching.md
content/docs/buildpack-author-guide/create-buildpack/make-buildpack-configurable.md
katacoda/scenarios/buildpack-author-guide/adding-bill-of-materials.md
katacoda/scenarios/buildpack-author-guide/caching.md
katacoda/scenarios/buildpack-author-guide/make-buildpack-configurable.md

Fix buildpack caching logic for API 0.6+

---

content/docs/features/bill-of-materials.md

Introduce the `pack sbom download` feature to users.

Document sbom download feature

---

themes/buildpacks/layouts/partials/footer.html

Add copyright footer

---

data/talks.yml
themes/buildpacks/layouts/shortcodes/talks.html

- Add KubeCon NA talk
- Display event name and year
- Reordered based on date/time recorded then based on comprehension level

Add KubeCon NA talk, display event information

---

katacoda/scenarios/app-developer-guide/background.sh
katacoda/scenarios/app-journey/background.sh
katacoda/scenarios/buildpack-author-guide/background.sh

Update the version of `pack` that is used in
our katacoda guide.

Updated pack version in katacoda

---

content/community.md

Add guidance on how to start contributing

---

data/pack/install.yml

This PR supports the following features:
Fixes #485
Signed-off-by: Conrad Taylor <conradwt@gmail.com>

Add script installation instructions for macOS.

---

content/docs/app-developer-guide/build-a-windows-app.md
themes/buildpacks/layouts/shortcodes/page-replace-toggle.html
tools/go.mod
tools/go.sum

Add instructions for Windows 2022

---

content/docs/app-developer-guide/build-a-windows-app.md

Signed-off-by: Javier Romero <rjavier@vmware.com>

Update Windows link

---

themes/buildpacks/layouts/index.html

Use YouTube embedded videos to demonstrate our wares.

Add front page example videos

---

content/docs/buildpack-author-guide/caching-strategies.md

Address issues in caching description

---

Makefile
themes/buildpacks/assets/scss/components/_hero.scss
themes/buildpacks/layouts/index.html

* [Style intro videos with use of icons](https://github.com/buildpacks/docs/commit/51e00eee6123188359aec65a8ecd2aa06672e7e8)
* [Fix hugo download for macOS](https://github.com/buildpacks/docs/commit/399410fec39482368e93435132403e832411255e)
Note: Organized the languages alphabetically.

Style intro videos with use of icons

---

content/docs/_index.md

(or we may want to remove it entirely given that the current roadmap is outdated)
Signed-off-by: narellano@vmware.com
Signed-off-by: Natalie Arellano <narellano@vmware.com>

Fix roadmap link

---

content/docs/buildpack-author-guide/create-buildpack/detection.md
katacoda/scenarios/buildpack-author-guide/detection.md

Update ANALYZING to RESTORING in the text as this change happened in API version 0.7.
fixes #517 
Signed-off-by: Aidan Delaney <adelaney21@bloomberg.net>

Reflect API 0.7 move to RESTORING

---

content/docs/buildpack-author-guide/create-buildpack/caching.md
katacoda/scenarios/buildpack-author-guide/caching.md

Fix code snippet that incorrectly truncated `bundler.toml`
fixes #518

Use append in code snippet

---

.github/workflows/main.yml
Makefile

While we await resolution of https://github.com/buildpacks/pack/issues/1574 this should fix the pack upgrade

Fix upgrade pack in CI

---

content/docs/buildpack-author-guide/build-phases-overview.md

Signed-off-by: Phil Nichol 35630607+philnichol@users.noreply.github.com
Signed-off-by: Phil Nichol <35630607+philnichol@users.noreply.github.com>

docs: Corrects a couple of typos

---

content/docs/buildpack-author-guide/create-buildpack/adding-bill-of-materials.md

Signed-off-by: Lars Gyrup Brink Nielsen <larsbrinknielsen@gmail.com>

docs: correct typo and expected Ruby version

---

content/docs/app-developer-guide/build-a-windows-app.md

Signed-off-by: Navdeep Pama <npama@vmware.com>

Resolves issue #556

---

content/docs/app-developer-guide/specify-buildpacks.md
content/docs/app-developer-guide/using-inline-buildpacks.md
content/docs/reference/config/project-descriptor.md

Update all occurrences of project descriptors to use the latest spec

Update all project descriptors to schema-version 0.2

---

content/docs/app-developer-guide/build-a-windows-app.md
content/docs/app-developer-guide/build-an-app.md
content/docs/app-journey.md
content/docs/buildpack-author-guide/create-buildpack/_index.md
content/docs/features/dockerfiles.md
themes/buildpacks/layouts/partials/docs.html

Replace some technical words and phrases with Simplified Technical English as described at
https://en.wikipedia.org/wiki/Simplified_Technical_English#Writing_rules

Address technical language review

---

content/docs/buildpack-author-guide/build-phases-overview.md

This fixes a small docs typo I found while browsing.

Updates hello world response documentation to reflect JSON

---

tools/get_pack_commands.go

Fixes https://github.com/buildpacks/docs/issues/668

Dynamically generate the alias for pack CLI documentation

---

content/docs/for-platform-operators/how-to/integrate-ci/pack/_index.md
content/docs/for-platform-operators/how-to/integrate-ci/pack/cli/_index.md
content/docs/for-platform-operators/how-to/integrate-ci/pack/concepts/_index.md

Should fix https://github.com/buildpacks/docs/issues/673

Fix pack aliases

---

content/docs/for-buildpack-authors/tutorials/basic-buildpack/01_setup-local-environment.md

Correctly format package.json in JSON
fixes #675

Provide valid example package.json

---

config.toml
content/community.md

Updated community page with more details and updated meeting information. Also removed the analytics link on our footer.

Updated Community page and removed analytics from footer

---

themes/buildpacks/layouts/index.html

Per feedback in this convo: https://github.com/buildpacks/docs/pull/680#discussion_r1542550144

Add more text to front page

---

content/docs/_index.md
data/talks.yml

Changes the location of the talks section from the landing page
Adds an overview paragraph to the landing page
Updates the level of few section headings in the Getting Started landing page
Changes the order of talks by time
Other minor edits

Updates the landing page

---

content/docs/for-buildpack-authors/how-to/write-buildpacks/use-exec.d.md

Provide documentation and examples of how to use exec.d

Document exec.d

---

.vale.ini
.vale/styles/confg/vocabularies/Buildpacks/accept.txt

Create a new vocab for use in the Buildpacks project

Add spelling exceptions for Buildpacks

---

content/docs/for-platform-operators/how-to/integrate-ci/tekton.md

Use the latest version of the tekton task

Update tekton task version

---

content/docs/for-buildpack-authors/how-to/write-buildpacks/add-labels.md
content/docs/for-buildpack-authors/how-to/write-buildpacks/clear-env.md
content/docs/for-buildpack-authors/how-to/write-buildpacks/create-layer.md
content/docs/for-buildpack-authors/how-to/write-buildpacks/get-started.md
content/docs/for-buildpack-authors/how-to/write-buildpacks/specify-env.md
content/docs/for-buildpack-authors/how-to/write-buildpacks/use-exec.d.md

Distinguish between build time and runtime environment variables
Explain `clear-env`

Add Buildpack environment explanation

---

data/pack/install.yml

- Update install on Arch Linux.

Update arch install

---

content/docs/for-buildpack-authors/tutorials/basic-buildpack/05_make-app-runnable.md

Ask the user to make the demo JS service runnable.
fixes: #810

Prompt user to uncomment code

---

.github/styles/config/vocabularies/Buildpacks/accept.txt
content/docs/for-platform-operators/how-to/integrate-ci/tekton.md

- Updated the tekton documentation to use the new buildpack task supporting the extension. 
- Issue: #814

Updated the tekton documentation to use the new buildpack task
