buildpacks/docs

src/content/docs/using-pack/install-pack.md
src/themes/buildpacks/layouts/shortcodes/latest.html

I sadly don't really have the chops to add Windows installation docs. I'll leave that as an exercise for others.
I also added a reusable shortcode that can infer the latest version using the GitHub Releases API.

Add pack installation instructions

---

content/docs/create-buildpack/build-app.md
content/docs/create-buildpack/building-blocks-cnb.md
content/docs/create-buildpack/caching.md
content/docs/create-buildpack/detection.md
content/docs/create-buildpack/make-app-runnable.md

- be more specific when referring to file to change
- add instruction to select a builder image
- PATH set up was not in the instructions but only in the final content
- fix double quote typo when making application runnable
We run through the tutorial and we found a few confusing things that we try to fix with this PR

Small correction on buildpack creation tutorial

---

content/docs/reference/buildpack-api.md

Adds more explanation of `api` in `buildpack.toml`, from this issue: https://github.com/buildpack/pack/issues/306
Specifically requested here: https://github.com/buildpack/docs/issues/66

Add blurb about api value in buildpack.toml

---

themes/buildpacks/layouts/partials/docs.html

Fixes the background as reported by @ameyer-pivotal

Fix docs container background

---

content/docs/app-developer-guide/build-an-app.md
content/docs/buildpack-author-guide/create-buildpack/make-app-runnable.md
content/docs/operator-guide/create-a-builder.md

This commit adds `--rm` option to all `docker run` in this document. Probably few want to keep a container in tutorials.
Note:  [content/docs/app-journey.md](https://github.com/buildpack/docs/blob/b20a878167ce6fb821377c114bd016842c606d5e/content/docs/app-journey.md) uses `docker run --rm`.

Add --rm to `docker run` to clean up containers

---

content/docs/concepts/components/builder.md

Minor typo fix `buidpacks` -> `buildpacks`
Signed-off-by: Jon Friesen <jfriesen@digitalocean.com>

fixes minor typo in builder.md

---

content/docs/buildpack-author-guide/create-buildpack/building-blocks-cnb.md

As reported in #79 and #68, the bionic cloudfoundry builder `cnbs/sample-builder:bionic` does not currently work for our tutorial as it does not have `wget` installed.
_NOTE: This is an interim solution until we can further update our tutorials to use the sample builders._
Resolves #79
Resolves #68

Remove bionic builder from create buildpack tutorial

---

themes/buildpacks/assets/scss/components/_docs.scss
themes/buildpacks/layouts/_default/baseof.html

This adds links to all `h2`, `h3`, `h4` elements for anchor links as suggested in https://github.com/buildpack/docs/issues/65.
I _think_ this works, but locally the anchor links weren't anchoring to the correct locations, so it would be useful to test this on some sort of staging environment if that exists.

Add anchor links for headers

---

content/docs/buildpack-author-guide/create-buildpack/make-buildpack-configurable.md

The buildpack example breaks in the case it finds an existing gemfile, but the checksum doesn't match, so it fails to create the folder.
After adding `|| true`, it no longer fails to build.
Signed-off-by: Dan Acristinii <dan.acristinii@swisscom.com>

Bundler no longer fails when there are gem updates

---

content/docs/buildpack-author-guide/create-buildpack/caching.md

This makes the cache page consistent with the code snippet on the subsequent page of the example.

Add p flag to mkdir

---

content/docs/reference/builder-config.md

This allows for linking to specific parts of the docs.
This PR also add clarification about default lifecycle version

Use headers for top-level keys in builder config documentation

---

content/docs/reference/builder-config.md

Something looks off with the docs. Going to revert for now. We might want to follow up with https://github.com/buildpacks/docs/issues/105

Revert "Use headers for top-level keys in builder config documentation"

---

.travis.yml

On the branch for https://github.com/buildpacks/docs/compare/anchor-builder-config?expand=1
without this change you see:
with this change you see:
- Resolves #105
Signed-off-by: Zander Mackie <zmackie@gmail.com>

Use newer version of hugo to match version available on homebrew

---

config.toml
content/docs/app-developer-guide/_index.md
content/docs/app-journey.md
content/docs/buildpack-author-guide/create-buildpack/_index.md
content/docs/install-pack.md
themes/buildpacks/layouts/partials/sidebar.html
themes/buildpacks/layouts/shortcodes/download-button.html
themes/buildpacks/layouts/shortcodes/summary.html

The [update to Hugo broke a few HTML features](https://discourse.gohugo.io/t/raw-html-getting-omitted-in-0-60-0/22032) we were using along with the Getting Started menu now iterating and displaying all pages instead of direct children.
This PR addresses these issues via:
1. Moving towards the use of shortcodes for things like consistent buttons.
2. Enabling html (marked as `unsafe`) in the new markdown engine as an immediate fix for other HTML embedded features.
3. Adding a property to top-level "getting-started" pages.

Fix download buttons and getting started sub-menu

---

themes/buildpacks/layouts/partials/footer.html

- Add link to mailing list in the footer
- Resolves https://github.com/buildpacks/docs/issues/91
Signed-off-by: Patrick Wiseman <patrick.wiseman@deft.services>

Add link to mailing list in the footer

---

content/docs/reference/reproducibility.md

- Fixes #112
Signed-off-by: Zander Mackie <zmackie@gmail.com>

Document reproducible builds

---

content/docs/reference/buildpack-api.md

The existing wording makes it seem like a string containing the contents of the build plan.

Buildpacks API: BUILD_PLAN is a path

---

content/docs/app-developer-guide/environment-variables.md

* By using the [bash-script](https://github.com/buildpacks/samples/tree/master/apps/bash-script) sample application, users can simply run the application afterwards, with minimal logging interfering with the hello-world buildpack logs
Fixes #130 

Make environment variable app runnable

---

content/docs/buildpack-author-guide/package-a-buildpack.md
content/docs/operator-guide/create-a-builder.md

* builder-config and package-config were deprecated in the latest release of pack
Close #159

Use config for create-builder and package-buildpack

---

content/docs/install-pack.md

Closes #7 
With the pushing of pack to Chocolatey [here](https://chocolatey.org/packages/pack), we can add it to our install pack documentation.

Add Chocolatey install for Windows

---

themes/buildpacks/layouts/index.html

Add Google App Engine as a Buildpack platform

---

content/docs/install-pack.md

brew command is available both on macOS and Linux. 
I rewrote the current Linux installation as alternative as using package manager is better than installing the binary into your path directly...

Update installation document

---

content/docs/concepts/components/platform.md

Add Platform documentation

---

content/docs/reference/spec/platform-api.md

Resolves #138 , which should help with https://github.com/spring-projects/spring-boot/issues/21122
I simply added a line (I figured that as a somewhat random requirement in the specification, it would be best to put it in the Platform API documentation). Let me know if it should be expanded upon!

Add initial non-root requirement documentation

---

themes/buildpacks/layouts/partials/header.html
themes/buildpacks/layouts/partials/sidebar.html
themes/buildpacks/layouts/partials/support.html

There were been warnings when building Hugo. This PR updates the template to use `Page.RelPermalink` in place of `Page.URL`, and protects against a nullpointer when accessing `.File.Path`

Fix hugo warnings when building

---

content/docs/app-developer-guide/environment-variables.md
content/docs/app-developer-guide/using-project-descriptor.md
content/docs/reference/config/project-descriptor.md

Resolves #165 
This PR adds documentation for the `project.toml` file, referred to as the project descriptor. It was proposed in https://github.com/buildpacks/rfcs/pull/32 and is specified [here](https://github.com/buildpacks/spec/blob/main/extensions/project-descriptor.md). 
As part of this PR, I am adding project.toml documentation:

Document project.toml

---

content/docs/app-developer-guide/run-an-app.md
content/docs/buildpack-author-guide/create-buildpack/_index.md
content/docs/buildpack-author-guide/create-buildpack/caching.md
content/docs/buildpack-author-guide/create-buildpack/make-app-runnable.md
content/docs/buildpack-author-guide/create-buildpack/make-buildpack-configurable.md
content/docs/buildpack-author-guide/create-buildpack/specify-multiple-process-types.md

Document launch process

---

content/docs/app-developer-guide/build-a-windows-app.md
content/docs/app-developer-guide/build-an-app.md
content/docs/app-developer-guide/environment-variables.md
content/docs/app-developer-guide/run-an-app.md
content/docs/app-developer-guide/specific-buildpacks.md
content/docs/app-developer-guide/using-project-descriptor.md
content/docs/app-journey.md
content/docs/buildpack-author-guide/package-a-buildpack.md
content/docs/concepts/operations/rebase.md
content/docs/operator-guide/create-a-builder.md
tools/go.mod
tools/go.sum

- Adds a Windows-centric guide to the App Developer Guides
- References new guide from the main App Journey tutorial, and from the Linux build guide
Signed-off-by: Andrew Meyer <meyeran@vmware.com>

Add Windows build guide

---

content/docs/concepts/components/builder.md

Feedback from @ekcasey here (https://github.com/buildpacks/rfcs/pull/116#discussion_r489565947) was:
> Also, not sure "executes the buildpacks against your app source code" is a correct description of builders. The lifecycle executes buildpacks. The builder is just an image, containing no start command, which platforms may use as an environment to execute the lifecycle.

Update builder summary to better reflect the process

---

content/docs/tools/pack/cli/install.md

Additional option to install pack CLI (using scoop) on Windows has been documented.
The new way of installation is possible due to ScoopInstaller/Main#1402.
Scoop's packages database is refreshed once a day so it will always install the latest version available.
Signed-off-by: Marcin Kłopotek <marcin.klopotek@gmail.com>

Add option to install pack CLI using scoop on Windows

---

content/docs/buildpack-author-guide/create-buildpack/build-app.md
content/docs/buildpack-author-guide/create-buildpack/building-blocks-cnb.md
content/docs/buildpack-author-guide/create-buildpack/caching.md
content/docs/buildpack-author-guide/create-buildpack/detection.md
content/docs/buildpack-author-guide/create-buildpack/make-buildpack-configurable.md

This change makes it so that the output is not checked against as part of the tests due to https://github.com/buildpacks/pack/issues/860.

Ignore output checks

---

content/docs/reference/config/package-config.md

Related: https://github.com/buildpacks/pack/pull/927
cc: @ameyer-pivotal @micahyoung @TisVictress

Add docs for 'platform.os' field in package.toml

---

content/docs/_index.md
themes/buildpacks/layouts/index.html
themes/buildpacks/layouts/partials/footer.html

https://www.cncf.io/blog/2020/11/18/toc-approves-cloud-native-buildpacks-from-sandbox-to-incubation/

Promoted to incubation from sandbox

---

content/docs/concepts/components/stack.md

Signed-off-by: Javier Romero <rjavier@vmware.com>
Resolves #262

Fix typo in example mixin label name

---

content/docs/app-developer-guide/build-an-app.md

Signed-off-by: Clivern <hello@clivern.com>
since the old command `pack suggest-builders` throws warning https://github.com/buildpacks/pack/blob/main/internal/commands/suggest_builders.go#L58

Replace pack suggest-builders with pack builder suggest command

---

content/docs/reference/spec/migration/buildpack-api-0.4-0.5.md

[Readable](https://github.com/yaelharel/docs/blob/migrationBuildpack45/content/docs/reference/spec/migration/buildpack-api-0.4-0.5.md)
Resolves #235

Add migration guide for buildpack api 0.4->0.5

---

content/docs/reference/spec/migration/_index.md
content/docs/reference/spec/migration/platform-api-0.3-0.4.md
content/docs/reference/spec/migration/platform-api-0.4-0.5.md

[Readable](https://github.com/buildpacks/docs/blob/feature/234-platform-0.4-0.5-migration/content/docs/reference/spec/migration/platform-api-0.4-0.5.md)
Resolves #234

Add migration guide for platform api 0.4 -> 0.5

---

content/docs/app-developer-guide/using-project-descriptor.md

Signed-off-by: dwillist <dthornton@vmware.com>
Just a brief mention of this syntax, seems like it is missing and was one of the reasons behind this bug report buildpacks/pack#987

add small mention of gitignore syntax

---

content/docs/app-developer-guide/using-cache-image.md

Signed-off-by: dwillist <dthornton@vmware.com>
This PR adds documentation for the `cache-image` flag. It should likely be expanded on with a section about how pack uses cache volumes & one about using cache images in CI. 
The PR does not use `ugo` to test the commands as they require docker hub authentication (which is difficult to automate).

Add docs for using the cache-image flag

---

config.toml

- Add a link to the registry in the navbar
Fixes buildpacks/registry-api#29

Add link to registry in the navbar

---

.github/workflows/main.yml

This is a temporary solution to unblock our pipelines but we'd want to figure out how to successfully upgrade to work with go1.16.
Context:
- [Failing build](https://github.com/buildpacks/docs/runs/1973682785?check_suite_focus=true)

Pin workflow (CI) to use go 1.15

---

.github/workflows/main.yml
Makefile
README.md

Fixes: https://github.com/buildpacks/docs/issues/311
`go install` behavior changed from 1.15 -> 1.16: the command no longer updates go.sum by default when packages are installed, causing the "missing packages" error. (related: https://github.com/golang/go/issues/44212)

Add -mod=mod flag to go install for build script

---

content/docs/concepts/components/builder.md

This is an attempt to make the builder the description of a builder more clear, in response to feedback that the current concept descriptions are confusing.

Clarify builder concept definition

---

data/pack/install.yml

Fixes a broken link to a Dockerfile that no longer exists now that we use buildpacks to build our pack container image.

Remove old Dockerfile reference

---

content/docs/_index.md
data/talks.yml
themes/buildpacks/assets/scss/_helpers.scss
themes/buildpacks/assets/scss/components/_talks.scss
themes/buildpacks/assets/scss/site.scss
themes/buildpacks/layouts/shortcodes/talks.html

Add a more integrated video talks into our Getting Started page along with "resources". In this initial pass, the resources associated to the talks are slides. I can foresee additional resources such as a git repository or tutorial workbook.
Resolves #127

Embed talk videos into docs page + add resources (slides)

---

content/docs/buildpack-author-guide/create-buildpack/adding-bill-of-materials.md
content/docs/buildpack-author-guide/create-buildpack/building-blocks-cnb.md
content/docs/buildpack-author-guide/create-buildpack/caching.md
content/docs/buildpack-author-guide/create-buildpack/detection.md

The BP authors guide seems to suggest creating buildpacks with ids that don't have a namespace. This is not compatible with buildpacks that will be published to a registry.

Fix buildpack ids to contain namespaces in the BP authors guide

---

content/docs/concepts/components/stack.md

Since as of #69, the "Builder Configuration" section no longer exists on:
https://buildpacks.io/docs/concepts/components/builder/
The link now targets the reference section instead:
https://buildpacks.io/docs/reference/config/builder-config/

Fix broken link to builder configuration file

---

content/docs/app-developer-guide/using-cache-image.md

Fix typo in the Cache Images guide

---

config.toml
themes/buildpacks/layouts/_default/baseof.html
themes/buildpacks/layouts/partials/footer.html

This change adds basic Google Analytics integrations as well as a link to the public [dashboard](https://datastudio.google.com/reporting/4b23856c-6c24-44f5-86f2-333d0ad3f236).
NOTE: Some fields are not populated yet due to the lack of data but should populate after a few days.
Resolves #346

Add Google Analytics and Dashboard

---

content/docs/concepts/_index.md
content/docs/concepts/components/_index.md
content/docs/concepts/components/lifecycle/_index.md
content/docs/concepts/components/lifecycle/analyze.md
content/docs/concepts/components/lifecycle/build.md
content/docs/concepts/components/lifecycle/create.md
content/docs/concepts/components/lifecycle/detect.md
content/docs/concepts/components/lifecycle/export.md
content/docs/concepts/components/lifecycle/launch.md
content/docs/concepts/components/lifecycle/rebase.md
content/docs/concepts/components/lifecycle/restore.md
themes/buildpacks/layouts/partials/docs.html

This is a polishing PR for original #358 by @natalieparellano .
- Don't expand lifecycle phases in sidebar
- Adhere to weight property in Components page
- Show summaries on Concepts page
_The intent of this PR is solely to provide minor changes to the original in an effort to reduce friction in the review and merging process. As author of the original PR, if there are any questions, comments, or concerns, don't hesitate to reach out to the maintainers._

Polish: Show summaries for lifecycle phases

---

.gitpod.yml
Makefile
README.md

This set of changes adds a small amount of configuration in order for setup on gitpod to be more "out-of-the-box". It properly maps the serving port and opens it in a preview.

Add Gitpod configuration

---

.gitpod.yml
Makefile
README.md
themes/buildpacks/layouts/_default/community.html

The previous slack button depended on slackin which we no longer use. This change now uses a simple static button.
_NOTE: Built on top of #371_

Fix Slack button in community page

---

content/community.md
themes/buildpacks/layouts/_default/community.html

- Added the community repo link to the html
- I've made the other changes to the community.md file. I reckon it will require some formatting, as I could not preview the changes myself. Is there a way to see the changes locally? 
- Should I look at jinja for syntax details or somewhere else? 
- Could not add a link for working group in RFCs section as the current link is broken (please see [here](https://github.com/buildpacks/community/issues/108))
In addition to the above, please let me know if any changes are to be made to the content itself.
See #373 and #357
cc: @jromero

Add contributor guide, link to community repo to community page

---

content/docs/app-developer-guide/environment-variables.md

Without that, the example is confusing since it does not use the `--descriptor` flag.
Signed-off-by: Mikey Boldt <mboldt@vmware.com>

Call out the default project descirptor location.

---

content/docs/app-developer-guide/using-http-proxy.md

Show how to both build an application behind a proxy and how an
application can be configured to access web APIs through a proxy.

Document how pack interacts with http proxies

---

Makefile
tools/get_pack_commands.go
tools/go.mod
tools/go.sum

1. Use `uname -m` instead of `uname -p` when determining architecture
2. Update pack to 0.22.0

Fix failing build on macOS and pipeline

---

data/calendar.yml

Adds a community calendar for community events.
The first event on the calendar is the recurring kpack working group. (cc: @matthewmcnew)

Add community calendar

---

themes/buildpacks/assets/scss/components/_docs.scss

Fixes #419
Signed-off-by: Prabin <acharyaprabin101@gmail.com

Fix content overlaying search dropdown in Getting started

---

content/docs/concepts/components/platform.md

I didn't see much value in having a hardcoded value for the current platform API. I changed the phrasing to point to the releases on the spec repo.
Resolves #439

Link to platform API releases

---

config.toml

Hugo 0.91 introduces a security context. We need to add the PACK_VERSION variable for things to work correctly.

Fix CI due to hugo upgrade

---

data/podman/setup.yml

Per comment: https://github.com/buildpacks/docs/issues/341#issuecomment-999685151

Add missing podman connection settings and info

---

content/docs/app-developer-guide/using-cache-image.md
katacoda/scenarios/app-developer-guide/using-cache-image.md

Fix typo in name of flag and fold typo fix in to katacoda
docs.

Fix typo in name of flag

---

.github/ISSUE_TEMPLATE/config.yml
README.md
config.toml
content/community.md
content/docs/_index.md
themes/buildpacks/layouts/_default/community.html

TODO:
Should we have instructions somewhere about the #buildpacks channels to find us or will people be able to figure it out?

move to slack links to CNCF slack

---

content/docs/app-developer-guide/build-a-windows-app.md
themes/buildpacks/layouts/_default/baseof.html
themes/buildpacks/layouts/shortcodes/page-replace-toggle-option.html
themes/buildpacks/layouts/shortcodes/page-replace-toggle.html

The builder to use for Windows containers is dependant on the environment docker is running on.
This change adds a toggle as well as a Windows 2004 version builder instructions.
Resolves https://github.com/buildpacks/pack/issues/1392

Add toggle for Windows tutorial

---

content/docs/buildpack-author-guide/create-buildpack/build-app.md
content/docs/buildpack-author-guide/create-buildpack/detection.md
katacoda/scenarios/buildpack-author-guide/build-app.md
katacoda/scenarios/buildpack-author-guide/detection.md
themes/buildpacks/layouts/partials/sidebar.html
tools/go.mod
tools/go.sum

When a user selects a sidebar menu entry, expand all the direct
children of that entry.
Signed-off-by: Aidan Delaney <adelaney21@bloomberg.net>

Expand current sidebar node

---

config.toml
themes/buildpacks/layouts/partials/header.html
themes/buildpacks/layouts/partials/sidebar.html

Reverts buildpacks/docs#539
I just noticed that this section bleeds into the homepage and looks very weird with multiple top navigation bars.
It also isn't responsive and looks bad on mobile screens. Reverting it for now until we can figure out a better way to display this. Ideally we should have something like - 
Notice the 'which are you' section 
https://web.archive.org/web/20210511112502/https://www.seldon.io/tech/

Revert "Promote guides to second level header"

---

content/docs/buildpack-author-guide/publishing-with-github-actions.md

In particular, the actions/checkout version is deprecated and will stop working soonish.
Signed-off-by: Lars Gyrup Brink Nielsen <larsbrinknielsen@gmail.com>

docs: update GitHub Actions dependencies in sample

---

.github/workflows/main.yml

Deemphasize katacoda in our docs.  We have been told that it is unlikely to be available in any form in future.
Signed-off-by: Aidan Delaney <adelaney21@bloomberg.net>

Remove requirement to sync katacoda docs

---

content/docs/buildpack-author-guide/create-buildpack/setup-local-environment.md

Ruby 3+ no longer includes webrick so it has to be explicitly required in the Gemfile for the app to start. Otherwise you'll get errors like this later on in the tutorial:
```
/layers/examples_ruby/ruby/lib/ruby/gems/3.1.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1755:in `detect_rack_handler': Server handler (thin,puma,reel,HTTP,webrick) not found. (RuntimeError)
from /layers/examples_ruby/ruby/lib/ruby/gems/3.1.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1493:in `run!'
from /layers/examples_ruby/ruby/lib/ruby/gems/3.1.0/gems/sinatra-2.1.0/lib/sinatra/main.rb:45:in `block in <module:Sinatra>'
```
See https://bugs.ruby-lang.org/issues/17303 for more details on the `webrick` removal. I also changed some of the string literals to use single quotes since that's more idiomatic in Ruby.

Update Gemfile in buildpack author guide

---

Makefile

This PR fixes an error downloading hugo on macOS when no installation is available
Fixes #572

Fix hugo download on macOS

---

content/docs/buildpack-author-guide/publishing-with-github-actions.md

Document the new way of producing outputs in a github action as the old way is deprecated and will be removed (31st May 2023).
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Replace deprecated GHA ::set-output syntax

---

content/docs/app-developer-guide/using-project-descriptor.md
content/docs/reference/config/project-descriptor.md

Use examples consistent with the current spec.  This specifies a top-level [_] table.

Update docs to project descriptor v2

---

data/talks.yml

The KubeCon EU talk is for a general audience, so is suitable for our list of generalist talks.

Add KubeCon EU 23 talk to talk list

---

content/docs/app-developer-guide/using-inline-buildpacks.md

Without this change, the inline buildpack fails to be executed.

fix: add missing .group to inline script

---

content/docs/app-developer-guide/specify-buildpacks.md
content/docs/app-developer-guide/using-project-descriptor.md
content/docs/reference/config/project-descriptor.md

Updates a few examples to include `schema-version` and adds a description of `schema-version` which links to spec materials.
Also, updates one page which had the `schema-version` set to `0.3`, which as far as I can tell is a typo.

Add missing `schema-version` properties

---

.github/workflows/main.yml
content/docs/buildpack-author-guide/create-buildpack/adding-bill-of-materials.md
content/docs/buildpack-author-guide/create-buildpack/building-blocks-cnb.md
content/docs/buildpack-author-guide/create-buildpack/caching.md
content/docs/buildpack-author-guide/create-buildpack/make-buildpack-configurable.md
content/docs/extension-guide/create-extension/build-dockerfile.md
content/docs/extension-guide/create-extension/building-blocks-extension.md
content/docs/extension-guide/create-extension/run-dockerfile.md
content/docs/extension-guide/create-extension/why-dockerfiles.md
katacoda/scenarios/buildpack-author-guide/adding-bill-of-materials.md
katacoda/scenarios/buildpack-author-guide/building-blocks-cnb.md
katacoda/scenarios/buildpack-author-guide/caching.md
katacoda/scenarios/buildpack-author-guide/make-buildpack-configurable.md

We don't need to re-create the builder, we just need to update the env vars passed to the buildpack to make it require things from extensions.
I wanted to make this fix as part of https://github.com/buildpacks/docs/pull/581, but that PR is blocked on there being new versions of pack and the lifecycle.

Fix extensions demo now that samples repo has been updated

---

content/docs/operator-guide/create-a-stack.md

Small change to make this tutorial mention `Jammy` instead of `Bionic` since that is what the rest of the doc references.

Update reference to Bionic in Stack tutorial

---

content/docs/app-developer-guide/using-cache-image.md

I updated the doc to reflect these changes https://github.com/buildpacks/lifecycle/pull/1136
* This PR solves #551 
* RFC tracking issue: https://github.com/buildpacks/rfcs/issues/268
* Original issue: https://github.com/buildpacks/lifecycle/issues/803

The platform won't delete cache images

---

content/docs/app-developer-guide/run-an-app.md
content/docs/buildpack-author-guide/create-buildpack/adding-bill-of-materials.md
katacoda/scenarios/app-developer-guide/run-an-app.md

Update the documentation about the `Rebasable` feature implementation
PR: https://github.com/buildpacks/pack/pull/1806
Issue: https://github.com/buildpacks/pack/issues/1799
Changes:
* Added a small description of the `Rebasable` label
* Updated the inspect-image outputs

Add Rebasable label small description and updated inspect-image outputs

---

content/docs/app-developer-guide/build-an-arm-app.md

Fixes #595 and adds a `z` option to the
`tar` extraction command.

Correctly unarchive ARM lifeccyle

---

content/docs/reference/spec/migration/platform-api-0.11-0.12.md

As it isn't implemented until 0.13 (whoops)

Remove cache cleanup from 0.12 migration 

---

content/docs/reference/config/builder-config.md

this will add docs for the pr [buildpacks/pack#1926](https://github.com/buildpacks/pack/pull/1926)

Docs for new [[build.env]] table in builder.toml

---

content/docs/buildpack-author-guide/create-buildpack/building-blocks-cnb.md

Update documentation: replace 'Ruby' with 'Node.js'
Changed the word 'Ruby' to 'Node.js' in the documentation to correct an inaccuracy with the previous content.

Patch 1 -Fixed Issue in building-blocks-cnb.md 

---

tools/get_pack_commands.go

When generating the pack cli docs, create aliases
using the older document structure

Generate older aliases to `pack` documentation

---

themes/buildpacks/layouts/index.html

We have developed a succinct description of what the project does. Include this on the front page before our claims about our heritage.

Update project description on front page

---

content/docs/for-app-developers/how-to/build-inputs/specify-export-target.md

There isn't a --layout flag, you invoke layout with the image name.

Fix reference to OCI layout feature in pack

---

data/calendar.yml

Removed community, office hours, and team leads ics calendar buttons since those do not contain anything to download (right now).

removed other ics calendars

---

content/docs/for-app-developers/how-to/special-cases/build-for-arm.md

There's finally a multi-arch builder publicly available, so this guide can be simplified substantially. It might also make sense to merge this with some of the content in this guide https://buildpacks.io/docs/for-app-developers/tutorials/basic-app/ at some point.

Update arm guide with arm-compatible builder instructions

---

content/docs/.common/concepts/composite-buildpack.md
content/docs/for-buildpack-authors/concepts/buildpack-group.md
content/docs/for-buildpack-authors/concepts/lifecycle-phases.md
content/docs/reference/config/buildpack-config.md
content/docs/reference/config/package-config.md

It should be called a "composite buildpack" but we can refer to the old name too

Fix references to "meta buildpack"

---

content/docs/for-app-developers/how-to/special-cases/build-for-arm.md

Updating the ARM build docs to reflect [`pack build --platform`](https://github.com/buildpacks/pack/pull/2162) support introduced in [`pack v0.34.0`](https://github.com/buildpacks/pack/releases/tag/v0.34.0).

Update ARM build docs

---

content/docs/for-platform-operators/how-to/build-inputs/create-builder/build-base.md

These extra slashes result in lines being unintentionally appended to previous `RUN` statements. This breaks the image build.
Removing them gives us the desired behavior.

fix build-base example

---

content/docs/for-buildpack-authors/how-to/write-buildpacks/add-labels.md
content/docs/for-buildpack-authors/how-to/write-buildpacks/use-exec.d.md

- Document image labels
- Edits the exec.d page 
Closes #733

Document image labels

---

content/docs/for-buildpack-authors/how-to/write-buildpacks/specify-launch-processes.md
content/docs/for-buildpack-authors/how-to/write-buildpacks/use-exec.d.md

Process types page
- Adds more content related to process types
- Reorganize the current content 
exec.d page 
- 1 styling edit (list item) 
Closes #735

Expand "Specify process types" page

---

content/docs/for-buildpack-authors/concepts/build-plan.md
content/docs/for-buildpack-authors/concepts/buildpack-group.md
content/docs/for-buildpack-authors/concepts/caching-strategies.md
content/docs/for-buildpack-authors/concepts/component-buildpack.md
content/docs/for-buildpack-authors/concepts/layer.md
content/docs/for-buildpack-authors/concepts/lifecycle-phases.md
content/docs/for-buildpack-authors/concepts/package.md
content/docs/for-buildpack-authors/concepts/targets.md
content/docs/for-buildpack-authors/how-to/write-buildpacks/use-build-plan.md
content/docs/for-buildpack-authors/how-to/write-buildpacks/use-exec.d.md

Expand buildpack author concepts pages
- Adds some content related to 4 pages under the author concepts section
- Minor MD styling of current content
- 1 typo fix
exec.d page
- 1 styling edit 
closes #740

Expand buildpack author concepts pages

---

content/docs/for-buildpack-authors/how-to/write-buildpacks/re-use-layers.md

- Adds details about re-using dependency layers
closes #749

expands re-use dependency layers page

---

content/docs/for-buildpack-authors/how-to/write-buildpacks/create-slice-layers.md

- Expands [Create slice layers](https://buildpacks.io/docs/for-buildpack-authors/how-to/write-buildpacks/create-slice-layers/) page
Closes #751

expand slice layers page

---

content/docs/for-app-developers/how-to/build-inputs/use-project-toml.md
content/docs/reference/config/project-descriptor.md

I found some [Google Cloud docs about this](https://cloud.google.com/docs/buildpacks/use-a-specific-builder), but they seem to be non-standard. This change adds a section explaining the standard way to set the builder.

Document builder property available in project descriptor

---

content/docs/for-app-developers/how-to/build-outputs/specify-launch-process.md

Remove mention of `pack` always treating `web` as the default process type. The `java-maven` buildpack [was updated](https://github.com/buildpacks/samples/commit/8fa4447e65145e5a727d203103c554bce2b085d6) to explicitly set the default process type (after the buildpack API version was bumped from 0.2 to 0.9, and [`pack` only sets the `web` process as default for < 0.6](https://github.com/buildpacks/spec/blob/main/platform.md#outputs-4)).
Also, the java-maven sample buildpack version is now [0.0.2](https://github.com/buildpacks/samples/commit/09460d909bc9f793e173e384f7396d4adbb07f3c).

Update specify-launch-process docs

---

content/docs/for-platform-operators/concepts/lifecycle/_index.md
content/docs/for-platform-operators/concepts/lifecycle/analyze.md
content/docs/for-platform-operators/concepts/lifecycle/build.md
content/docs/for-platform-operators/concepts/lifecycle/create.md
content/docs/for-platform-operators/concepts/lifecycle/detect.md
content/docs/for-platform-operators/concepts/lifecycle/export.md
content/docs/for-platform-operators/concepts/lifecycle/extend.md
content/docs/for-platform-operators/concepts/lifecycle/launch.md
content/docs/for-platform-operators/concepts/lifecycle/rebase.md
content/docs/for-platform-operators/concepts/lifecycle/restore.md

Expand Platform lifecycle/phases pages
- Adds some content related to the platform lifecycle/phases section
- Adds links to the specs
- Minor MD styling of current content
- Update broken links 
closes #766

Update existing lifecycle phases (Platform)

---

content/docs/for-platform-operators/concepts/base-images.md
content/docs/for-platform-operators/concepts/build-run-images.md
content/docs/for-platform-operators/concepts/builder.md

- adds build and run images content under the platform section

Adds Build time and runtime images content to the Platform docs

---

content/docs/for-platform-operators/tutorials/lifecycle/_index.md

When a Mac users exports the artifacts built by the `builder`, the `launcher` executable packaged into an OCI image must be linux arm64 in the tutorial.
I've tried to follow this tutorial on a Apple M1.

Linux arm64 launcher required for Mac users

---

content/docs/for-buildpack-authors/concepts/buildpack-group.md
themes/buildpacks/layouts/_default/baseof.html

Upgraded jQuery version to latest(3.7.1) and Axios to 1.7.9

Chore: Upgrade jQuery and Axios version

---

content/docs/for-app-developers/how-to/build-inputs/configure-build-time-environment.md

In [Use project.toml](https://buildpacks.io/docs/for-app-developers/how-to/build-inputs/use-project-toml/) it is suggested to add env vars under [[io.buildpacks.build.env]] and not under [[build.env]], which seems incorrect.

Fix documentation on project.toml env vars
